Repository playcanvas/splat-transform, pull requests merged in 2025-09, with the labels that each got.

#42 Structure fixes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .npmrc
  eslint.config.mjs
  package-lock.json
  package.json
  release.sh
  rollup.config.mjs
Labels: documentation

#46 Add sog sh meta
  src/writers/write-sog.ts
Labels: enhancement

#47 Remove sharp, jsdom, node-canvas
  lib/BUILD.md
  lib/webp_encode.c
  lib/webp_encode.mjs
  lib/webp_encode.wasm
  package-lock.json
  package.json
  rollup.config.mjs
  src/global.d.ts
  src/gpu/gpu-device.ts
  src/index.ts
  src/process.ts
  src/utils/webp.ts
  src/writers/write-sog.ts
  tsconfig.json
Labels: enhancement

#67 Improve --filterNaN
  src/process.ts
Labels: bug
